version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build_and_test:
    machine:
      image: ubuntu-2204:2024.01.1
    steps:
      - checkout
      - node/install:
          node-version: '22.3'
      - run:
          name: Install requirements
          command: npm ci
      - run:
          name: Run tests
          command: npm run test
  publish:
    machine:
      image: ubuntu-2204:2024.01.1
    steps:
      - checkout
      - node/install:
          node-version: '22.3'
      - run:
          name: Install requirements
          command: npm ci
      - run:
          name: Authenticate with NPM registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Semantic Release
          command: npm run semantic-release
  validate_main_version:
    machine:
      image: ubuntu-2204:2024.01.1
    steps:
      - checkout
      - run:
          name: Validate version
          command: ./bin/ci_validate_version.sh
  semantic_release:
    machine:
      image: ubuntu-2204:2024.01.1
      resource_class: large
    steps:
      - checkout
      - node/install:
          node-version: '22.3'
      - run:
          name: Install requirements
          command: npm ci
      - run:
          name: Semantic Release
          command: npm run semantic-release

workflows:
  CI:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - main
                - dev
      - require_approval:
          type: approval
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - main
                - dev
      - publish:
          requires:
            - build_and_test
            - require_approval
          filters:
            branches:
              only:
                - main
                - dev
      - semantic_release:
          requires:
            - publish
          filters:
            branches:
              only:
                - main