name: ci

on:
  push:
    branches:
      - "hiep-test"

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_node_lint_test.yml@v0.9.0
    runs-on: ubuntu-24.04-8core
    with:
      run-build: true
      run-unit-tests: true
      node-version: 24
