name: ci

on:
  push:
    branches:
      - "hiep-test"

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_node_lint_test.yml@hiep-test
    with:
      run-build: true
      run-unit-tests: true
      node-version: 24
